server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false

spring:
  thymeleaf:
    cache: false

filebridge:
  demo-mode: true
  local-root: local-data
  demo-remote-root: demo-remote-data
  remote-root: /
  users:
    - username: admin
      password: Change_ME
      role: ADMIN
      root-path: /
    - username: intern
      password: Change_ME
      role: VIEWER
      root-path: /Intern
    - username: extern
      password: Change_ME
      role: EDITOR
      root-path: /Extern
